### PR TITLE
add film title as tooltip

### PR DESCRIPTION
**Pull request by maxkele**

### CODE REVIEW

**Comment by maxkele** [comment]
Theres a Type error but I can't tell where it's happening

**Comment by qjack001** [comment]
> Theres a Type error but I can't tell where it's happening

I think you were close, just missing the instantiation in the `main.ts` I've pushed a commit to see if that fixes it

**Comment by qjack001** [comment]
Ok that did the trick. just needs to be styled now

**Comment by maxkele** [comment]
Its a bit weird with how it's styling but I kinda like it as "invisible" but with following to be visible over the red

**Comment by qjack001** [comment]
> Its a bit weird with how it's styling but I kinda like it as "invisible" but with following to be visible over the red

Ya that's actually a really cool effect

**Review by qjack001 — APPROVED** [review]

**Pull request merged**
